version: "3"
services:
  app:
    container_name: mdsync-api
    restart: always
    build: ./
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGODB_URI: mongodb://almalif:secret@mongo:27017/mdsync_db?authSource=mdsync_db
  mongo:
    container_name: mdsync-db
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ./.db/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mdsync_db
      MONGO_NON_ROOT_USERNAME: almalif
      MONGO_NON_ROOT_PASSWORD: secret
      MONGO_NON_ROOT_ROLE: readWrite
